# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LocationListViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocationListViewer
  pod 'Mapbox-iOS-SDK', '~> 5.7'
  pod 'MapboxDirections.swift', '0.20.0'


end
